pub const LOREM_IPSUM: &str = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.";

pub const BACON_IPSUM: &str = "Bacon ipsum dolor amet filet mignon porchetta bresaola pastrami flank landjaeger burgdoggen shank andouille. Tri-tip chislic pork ham hock leberkas spare ribs t-bone beef ribs pork belly fatback. Cupim leberkas turducken flank, tail ground round chuck capicola short loin meatloaf tongue bresaola brisket. Bresaola pancetta sirloin, pork landjaeger jowl ground round cupim beef ham. Buffalo venison hamburger, shank meatloaf tongue spare ribs burgdoggen.";

pub const CAT_IPSUM: &str = "Vommit food and eat it again kitty ipsum dolor sit amet, shed everywhere shed everywhere stretching attack your ankles chase the red dot, hairball run catnip eat the grass sniff and bawl under human beds claw your carpet in places everyone can see - why hide my amazing artistic clawing skills? lick sellotape. I could pee on this if i had the energy vommit food and eat it again plan steps for world domination. Chase dog then run away tuxedo cats always looking dapper lick face hiss at owner, pee a lot, and meow repeatedly scratch at fence purrrrrr eat muffins and poutine until owner comes back. Trip on catnip if it smells like fish eat as much as you wish poop on floor and watch human clean up, for hide head under blanket so no one can see ignore the human until she needs to get up, then climb on her lap and sprawl and kitty scratches couch bad kitty where is it? i saw that bird i need to bring it home to mommy squirrel! . I cry and cry and cry unless you pet me, and then maybe i cry just for fun munch on tasty moths. Why dog in house? i'm the sole ruler of this home and its inhabitants smelly, stupid dogs, inferior furballs time for night-hunt, human freakout whenever a door is opened, rush in before the human, but i will ruin the couch with my claws. Make it to the carpet before i vomit mmmmmm swat at dog, and jump launch to pounce upon little yarn mouse, bare fangs at toy run hide in litter box until treats are fed. What a cat-ass-trophy! furball roll roll roll so hiiiiiiiiii feed me now for sleep all day whilst slave is at work, play all night whilst slave is sleeping so meow. Chase red laser dot. Pretend not to be evil stand in front of the computer screen, but howl uncontrollably for no reason so take a big fluffing crap ðŸ’© so scratch the box dream about hunting birds, chew foot. Sleep on dog bed, force dog to sleep on floor.";

pub const HIPSTER_IPSUM: &str = "I\'m baby fam JOMO pickled chicharrones echo park polaroid, roof party lumbersexual celiac marfa vaporware. Literally fixie poke, roof party mukbang umami kinfolk 3 wolf moon ramps pop-up wayfarers iPhone ethical cardigan. Pork belly pinterest four loko lumbersexual mustache live-edge cliche. Mlkshk DSA shaman coloring book poutine, JOMO cray bushwick vape. Cred vinyl unicorn chicharrones, four loko taiyaki celiac gentrify literally raclette asymmetrical pinterest you probably haven't heard of them put a bird on it. Neutra seitan post-ironic bushwick prism before they sold out ennui skateboard shaman, DIY flannel VHS. Tilde poutine etsy, shabby chic 8-bit chia pug.";

pub const ZOMBIE_IPSUM: &str = "Zombie ipsum reversus ab viral inferno, nam rick grimes malum cerebro. De carne lumbering animata corpora quaeritis. Summus brains sit​​, morbo vel maleficia? De apocalypsi gorger omero undead survivor dictum mauris. Hi mindless mortuis soulless creaturas, imo evil stalking monstra adventus resi dentevil vultus comedat cerebella viventium. Qui animated corpse, cricket bat max brucks terribilem incessu zomby. The voodoo sacerdos flesh eater, suscitat mortuos comedere carnem virus. Zonbi tattered for solum oculi eorum defunctis go lum cerebro. Nescio brains an Undead zombies. Sicut malus putrid voodoo horror. Nigh tofth eliv ingdead.";

pub const DELOREAN_IPSUM: &str = "I'm gonna ram him. Marty, will we ever see you again? Alright, good-bye Einy. Oh, watch that re-entry, it's a little bumpy. Doc, wait. No, bastards. The only way we're gonna get those two to successfully meet is if they're alone together. So you've got to get your father and mother to interact at some sort of social-Now, of course not, Biff, now, I wouldn't want that to happen. I'm too loud. I can't believe it. I'm never gonna get a chance to play in front of anybody. I don't worry. this is all wrong. I don't know what it is but when I kiss you, it's like kissing my brother. I guess that doesn't make any sense, does it? Where the hell are they. This Saturday night, mostly clear, with some scattered clouds. Lows in the upper forties. I guarantee it. Excuse me. Biff. Doc, you don't just walk into a store and ask for plutonium. Did you rip this off? Lorraine, have you ever, uh, been in a situation where you know you had to act a certain way but when you got there, you didn't know if you could go through with it?";

pub const PIRATE_IPSUM: &str = "Prow scuttle parrel provost Sail ho shrouds spirits boom mizzenmast yardarm. Pinnace holystone mizzenmast quarter crow's nest nipperkin grog yardarm hempen halter furl. Swab barque interloper chantey doubloon starboard grog black jack gangway rutters. Deadlights jack lad schooner scallywag dance the hempen jig carouser broadside cable strike colors. Bring a spring upon her cable holystone blow the man down spanker Shiver me timbers to go on account lookout wherry doubloon chase. Belay yo-ho-ho keelhaul squiffy black spot yardarm spyglass sheet transom heave to. Trysail Sail ho Corsair red ensign hulk smartly boom jib rum gangway. Case shot Shiver me timbers gangplank crack Jennys tea cup ballast Blimey lee snow crow's nest rutters. Fluke jib scourge of the seven seas boatswain schooner gaff booty Jack Tar transom spirits.";
